"""add_pharmacy_bypass_rule_link

Revision ID: s0m5n34o789n
Revises: r9l4n23o678m
Create Date: 2025-12-29

Adds pharmacy_id FK to bypass_rules table to link auto-created bypass rules
to their source pharmacy. Also creates bypass rules for existing pharmacies
that have whatsapp_phone_number set.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "s0m5n34o789n"
down_revision: Union[str, Sequence[str], None] = "r9l4n23o678m"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add pharmacy_id FK to bypass_rules and create rules for existing pharmacies."""

    # 1. Add pharmacy_id column to bypass_rules
    op.add_column(
        "bypass_rules",
        sa.Column(
            "pharmacy_id",
            sa.UUID(),
            nullable=True,
            comment="Pharmacy that auto-created this rule (NULL for manual rules)",
        ),
        schema="core",
    )

    # 2. Create foreign key constraint
    op.create_foreign_key(
        "fk_bypass_rules_pharmacy",
        "bypass_rules",
        "pharmacy_merchant_configs",
        ["pharmacy_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
        ondelete="SET NULL",
    )

    # 3. Create index for efficient lookups
    op.create_index(
        "idx_bypass_rules_pharmacy_id",
        "bypass_rules",
        ["pharmacy_id"],
        schema="core",
    )

    # 4. Create bypass rules for existing pharmacies with whatsapp_phone_number
    conn = op.get_bind()
    result = conn.execute(
        sa.text("""
            SELECT id, organization_id, pharmacy_name, whatsapp_phone_number
            FROM core.pharmacy_merchant_configs
            WHERE whatsapp_phone_number IS NOT NULL
        """)
    )

    for row in result:
        pharmacy_id = row.id
        org_id = row.organization_id
        pharmacy_name = row.pharmacy_name
        whatsapp_number = row.whatsapp_phone_number

        # Generate rule name
        short_id = str(pharmacy_id)[:8]
        safe_name = pharmacy_name.replace(" ", "_")[:30] if pharmacy_name else "Farmacia"
        rule_name = f"pharmacy_bypass_{safe_name}_{short_id}"

        # Insert bypass rule
        conn.execute(
            sa.text("""
                INSERT INTO core.bypass_rules
                (id, organization_id, pharmacy_id, rule_name, description, rule_type,
                 phone_number_id, target_agent, priority, enabled, created_at, updated_at)
                VALUES (
                    gen_random_uuid(),
                    :org_id,
                    :pharmacy_id,
                    :rule_name,
                    :description,
                    'whatsapp_phone_number_id',
                    :phone_id,
                    'pharmacy_operations_agent',
                    100,
                    true,
                    NOW(),
                    NOW()
                )
                ON CONFLICT (organization_id, rule_name) DO NOTHING
            """),
            {
                "org_id": org_id,
                "pharmacy_id": pharmacy_id,
                "rule_name": rule_name,
                "description": f"Auto-generated bypass rule for pharmacy: {pharmacy_name}",
                "phone_id": whatsapp_number,
            },
        )


def downgrade() -> None:
    """Remove pharmacy_id FK from bypass_rules."""
    # Drop index
    op.drop_index(
        "idx_bypass_rules_pharmacy_id",
        table_name="bypass_rules",
        schema="core",
    )

    # Drop foreign key
    op.drop_constraint(
        "fk_bypass_rules_pharmacy",
        "bypass_rules",
        schema="core",
        type_="foreignkey",
    )

    # Drop column
    op.drop_column("bypass_rules", "pharmacy_id", schema="core")
