"""initial_schema_migration

Revision ID: ad98b04fa4ed
Revises: 
Create Date: 2025-11-30 21:51:22.421469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ad98b04fa4ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Document title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full document content in markdown/plain text'),
    sa.Column('document_type', postgresql.ENUM('mission_vision', 'contact_info', 'software_catalog', 'faq', 'clients', 'success_stories', 'general', name='document_type_enum'), nullable=False, comment='Type of document for categorization'),
    sa.Column('category', sa.String(length=200), nullable=True, comment='Secondary category for finer classification'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True, comment='Tags for flexible categorization and filtering'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible metadata storage (author, source, version, etc.)'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether this document is active and searchable'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Vector embedding for semantic similarity search'),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True, comment='Full-text search vector (auto-generated from title + content)'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='Order for displaying documents (lower = first)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_knowledge_category', 'company_knowledge', ['category'], unique=False, schema='core')
    op.create_index('idx_knowledge_embedding_hnsw', 'company_knowledge', ['embedding'], unique=False, schema='core', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_knowledge_search_vector', 'company_knowledge', ['search_vector'], unique=False, schema='core', postgresql_using='gin')
    op.create_index('idx_knowledge_tags', 'company_knowledge', ['tags'], unique=False, schema='core', postgresql_using='gin')
    op.create_index('idx_knowledge_type_active', 'company_knowledge', ['document_type', 'active'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_knowledge_active'), 'company_knowledge', ['active'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_knowledge_category'), 'company_knowledge', ['category'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_knowledge_document_type'), 'company_knowledge', ['document_type'], unique=False, schema='core')
    op.create_table('contact_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wa_id', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('assigned_method', sa.String(length=50), nullable=False),
    sa.Column('domain_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_contact_domains_assigned_at', 'contact_domains', ['assigned_at'], unique=False, schema='core')
    op.create_index('idx_contact_domains_domain', 'contact_domains', ['domain'], unique=False, schema='core')
    op.create_index('idx_contact_domains_method', 'contact_domains', ['assigned_method'], unique=False, schema='core')
    op.create_index('idx_contact_domains_wa_id', 'contact_domains', ['wa_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_contact_domains_domain'), 'contact_domains', ['domain'], unique=False, schema='core')
    op.create_index(op.f('ix_core_contact_domains_wa_id'), 'contact_domains', ['wa_id'], unique=True, schema='core')
    op.create_table('domain_configs',
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.String(length=10), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('service_class', sa.String(length=100), nullable=True),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('fallback_enabled', sa.String(length=10), nullable=True),
    sa.Column('config_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('domain'),
    schema='core'
    )
    op.create_index('idx_domain_configs_enabled', 'domain_configs', ['enabled'], unique=False, schema='core')
    op.create_index('idx_domain_configs_priority', 'domain_configs', ['priority'], unique=False, schema='core')
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique organization identifier'),
    sa.Column('slug', sa.String(length=50), nullable=False, comment="URL-friendly unique identifier (e.g., 'acme-corp')"),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Official organization name'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='Display name for UI (falls back to name)'),
    sa.Column('mode', sa.String(length=20), nullable=False, comment="Operating mode: 'generic' uses static config, 'multi_tenant' uses DB config"),
    sa.Column('llm_model', sa.String(length=100), nullable=False, comment='Default LLM model for this tenant'),
    sa.Column('llm_temperature', sa.Float(), nullable=False, comment='Default temperature for LLM (0.0-1.0)'),
    sa.Column('llm_max_tokens', sa.Integer(), nullable=False, comment='Max tokens for LLM responses'),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Feature flags (e.g., {'rag_enabled': true, 'custom_agents': false})"),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='Maximum users allowed in organization'),
    sa.Column('max_documents', sa.Integer(), nullable=False, comment='Maximum documents in knowledge base'),
    sa.Column('max_agents', sa.Integer(), nullable=False, comment='Maximum custom agents'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Organization status: 'active', 'suspended', 'trial'"),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True, comment='Trial expiration date (null if not on trial)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_organizations_created_at', 'organizations', ['created_at'], unique=False, schema='core')
    op.create_index('idx_organizations_mode', 'organizations', ['mode'], unique=False, schema='core')
    op.create_index('idx_organizations_slug', 'organizations', ['slug'], unique=False, schema='core')
    op.create_index('idx_organizations_status', 'organizations', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_organizations_slug'), 'organizations', ['slug'], unique=True, schema='core')
    op.create_index(op.f('ix_core_organizations_status'), 'organizations', ['status'], unique=False, schema='core')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False, schema='core')
    op.create_index('idx_users_disabled', 'users', ['disabled'], unique=False, schema='core')
    op.create_index('idx_users_email', 'users', ['email'], unique=False, schema='core')
    op.create_index('idx_users_username', 'users', ['username'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_index(op.f('ix_core_users_username'), 'users', ['username'], unique=True, schema='core')
    op.create_table('credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='risklevel'), nullable=False),
    sa.Column('used_credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pending_charges', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('minimum_payment_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'ACTIVE', 'BLOCKED', 'OVERDUE', 'SUSPENDED', 'CLOSED', 'DEFAULTED', name='accountstatus'), nullable=False),
    sa.Column('collection_status', sa.Enum('NONE', 'SOFT_REMINDER', 'FORMAL_NOTICE', 'COLLECTION_AGENCY', 'LEGAL_ACTION', 'WRITTEN_OFF', name='collectionstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('last_statement_date', sa.Date(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_on_time_payments', sa.Integer(), nullable=False),
    sa.Column('consecutive_late_payments', sa.Integer(), nullable=False),
    sa.Column('total_payments_made', sa.Integer(), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('last_collection_action', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='credit'
    )
    op.create_index(op.f('ix_credit_credit_accounts_account_number'), 'credit_accounts', ['account_number'], unique=True, schema='credit')
    op.create_index(op.f('ix_credit_credit_accounts_customer_id'), 'credit_accounts', ['customer_id'], unique=False, schema='credit')
    op.create_index(op.f('ix_credit_credit_accounts_id'), 'credit_accounts', ['id'], unique=False, schema='credit')
    op.create_index(op.f('ix_credit_credit_accounts_status'), 'credit_accounts', ['status'], unique=False, schema='credit')
    op.create_table('analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index(op.f('ix_ecommerce_analytics_metric_name'), 'analytics', ['metric_name'], unique=False, schema='ecommerce')
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('reputation', sa.String(length=50), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('warranty_years', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('external_code', sa.String(length=100), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ecommerce'
    )
    op.create_index('idx_brands_active', 'brands', ['active'], unique=False, schema='ecommerce')
    op.create_index('idx_brands_name_trgm', 'brands', ['name'], unique=False, schema='ecommerce', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ecommerce'
    )
    op.create_index('idx_categories_active', 'categories', ['active'], unique=False, schema='ecommerce')
    op.create_index('idx_categories_sort', 'categories', ['sort_order'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_categories_external_id'), 'categories', ['external_id'], unique=False, schema='ecommerce')
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('profile_name', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('total_inquiries', sa.Integer(), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('preferred_brands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('vip', sa.Boolean(), nullable=True),
    sa.Column('first_contact', sa.DateTime(), nullable=True),
    sa.Column('last_contact', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index('idx_customers_active', 'customers', ['active'], unique=False, schema='ecommerce')
    op.create_index('idx_customers_name', 'customers', ['first_name', 'last_name'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_customers_phone_number'), 'customers', ['phone_number'], unique=True, schema='ecommerce')
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('min_purchase_amount', sa.Float(), nullable=True),
    sa.Column('applicable_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index(op.f('ix_ecommerce_promotions_active'), 'promotions', ['active'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_promotions_promo_code'), 'promotions', ['promo_code'], unique=True, schema='ecommerce')
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.Enum('GENERAL_PRACTICE', 'CARDIOLOGY', 'DERMATOLOGY', 'EMERGENCY', 'ENDOCRINOLOGY', 'GASTROENTEROLOGY', 'GYNECOLOGY', 'NEUROLOGY', 'ONCOLOGY', 'OPHTHALMOLOGY', 'ORTHOPEDICS', 'PEDIATRICS', 'PSYCHIATRY', 'PULMONOLOGY', 'RADIOLOGY', 'SURGERY', 'UROLOGY', name='doctorspecialty'), nullable=False),
    sa.Column('secondary_specialties', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('working_days', sa.JSON(), nullable=True),
    sa.Column('working_hours_start', sa.Time(), nullable=True),
    sa.Column('working_hours_end', sa.Time(), nullable=True),
    sa.Column('appointment_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    schema='healthcare'
    )
    op.create_index(op.f('ix_healthcare_doctors_id'), 'doctors', ['id'], unique=False, schema='healthcare')
    op.create_index(op.f('ix_healthcare_doctors_license_number'), 'doctors', ['license_number'], unique=True, schema='healthcare')
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_email', sa.String(length=255), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('current_medications', sa.JSON(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=50), nullable=True),
    sa.Column('insurance_group_number', sa.String(length=50), nullable=True),
    sa.Column('insurance_valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DECEASED', 'TRANSFERRED', name='patientstatus'), nullable=False),
    sa.Column('last_vitals', sa.JSON(), nullable=True),
    sa.Column('last_vitals_date', sa.DateTime(), nullable=True),
    sa.Column('medical_record_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='healthcare'
    )
    op.create_index(op.f('ix_healthcare_patients_id'), 'patients', ['id'], unique=False, schema='healthcare')
    op.create_index(op.f('ix_healthcare_patients_medical_record_number'), 'patients', ['medical_record_number'], unique=True, schema='healthcare')
    op.create_index(op.f('ix_healthcare_patients_national_id'), 'patients', ['national_id'], unique=True, schema='healthcare')
    op.create_index(op.f('ix_healthcare_patients_phone'), 'patients', ['phone'], unique=False, schema='healthcare')
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompts_is_dynamic', 'prompts', ['is_dynamic'], unique=False)
    op.create_index(op.f('ix_prompts_key'), 'prompts', ['key'], unique=True)
    op.create_index('ix_prompts_key_active', 'prompts', ['key', 'is_active'], unique=False)
    op.create_table('organization_users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique membership identifier'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization this membership belongs to'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who is a member of the organization'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="User role: 'owner', 'admin', 'member'"),
    sa.Column('personal_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='User-specific settings overrides (e.g., default_domain, ui_preferences)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user'),
    schema='core'
    )
    op.create_index('idx_org_users_org_id', 'organization_users', ['organization_id'], unique=False, schema='core')
    op.create_index('idx_org_users_role', 'organization_users', ['role'], unique=False, schema='core')
    op.create_index('idx_org_users_user_id', 'organization_users', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_organization_users_organization_id'), 'organization_users', ['organization_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_organization_users_user_id'), 'organization_users', ['user_id'], unique=False, schema='core')
    op.create_table('tenant_agents',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique agent configuration identifier'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization this agent belongs to'),
    sa.Column('agent_key', sa.String(length=100), nullable=False, comment="Unique key for this agent (e.g., 'product_agent')"),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment="Agent type: 'domain', 'specialized', 'custom'"),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='Human-readable agent name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of what this agent does'),
    sa.Column('agent_class', sa.String(length=255), nullable=True, comment="Full Python class path for custom agents (e.g., 'app.custom.MyAgent')"),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this agent is active'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority for routing (higher = preferred)'),
    sa.Column('domain_key', sa.String(length=50), nullable=True, comment='Associated domain key (for domain agents)'),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False, comment='Keywords that trigger this agent'),
    sa.Column('intent_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Patterns for intent matching (e.g., [{pattern: '...', weight: 1.0}])"),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Agent-specific configuration (model, temperature, tools, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'agent_key', name='uq_org_agent_key'),
    schema='core'
    )
    op.create_index('idx_tenant_agents_agent_type', 'tenant_agents', ['agent_type'], unique=False, schema='core')
    op.create_index('idx_tenant_agents_domain_key', 'tenant_agents', ['domain_key'], unique=False, schema='core')
    op.create_index('idx_tenant_agents_enabled', 'tenant_agents', ['enabled'], unique=False, schema='core')
    op.create_index('idx_tenant_agents_org_id', 'tenant_agents', ['organization_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_agents_domain_key'), 'tenant_agents', ['domain_key'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_agents_enabled'), 'tenant_agents', ['enabled'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_agents_organization_id'), 'tenant_agents', ['organization_id'], unique=False, schema='core')
    op.create_table('tenant_configs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique configuration identifier'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization this config belongs to'),
    sa.Column('enabled_domains', postgresql.ARRAY(sa.String()), nullable=False, comment="List of enabled domain keys (e.g., ['ecommerce', 'healthcare'])"),
    sa.Column('default_domain', sa.String(length=50), nullable=False, comment='Default domain for routing when intent is unclear'),
    sa.Column('enabled_agent_types', postgresql.ARRAY(sa.String()), nullable=False, comment='List of enabled agent keys (empty = all builtin)'),
    sa.Column('agent_timeout_seconds', sa.Integer(), nullable=False, comment='Timeout for agent operations in seconds'),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False, comment='Whether RAG is enabled for this tenant'),
    sa.Column('rag_similarity_threshold', sa.Float(), nullable=False, comment='Minimum similarity score for RAG results (0.0-1.0)'),
    sa.Column('rag_max_results', sa.Integer(), nullable=False, comment='Maximum number of results from RAG search'),
    sa.Column('prompt_scope', sa.String(length=20), nullable=False, comment="Prompt resolution scope: 'system', 'global', 'org'"),
    sa.Column('whatsapp_phone_number_id', sa.String(length=50), nullable=True, comment='WhatsApp Business phone number ID (overrides global)'),
    sa.Column('whatsapp_verify_token', sa.String(length=255), nullable=True, comment='Webhook verification token (overrides global)'),
    sa.Column('advanced_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional configuration (rate limits, custom settings)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id'),
    schema='core'
    )
    op.create_index('idx_tenant_configs_org_id', 'tenant_configs', ['organization_id'], unique=False, schema='core')
    op.create_table('tenant_documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique document identifier'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization this document belongs to'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Document title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full document content in markdown/plain text'),
    sa.Column('document_type', sa.String(length=100), nullable=False, comment='Type classification (faq, guide, policy, product_info, etc.)'),
    sa.Column('category', sa.String(length=200), nullable=True, comment='Secondary category for finer classification'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='Flexible tags for filtering and categorization'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metadata (author, source, version, language, etc.)'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Vector embedding for semantic similarity search'),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True, comment='Full-text search vector (auto-generated from title + content)'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether this document is active and searchable'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Order for displaying documents (lower = first)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_tenant_docs_category', 'tenant_documents', ['category'], unique=False, schema='core')
    op.create_index('idx_tenant_docs_org_active', 'tenant_documents', ['organization_id', 'active'], unique=False, schema='core')
    op.create_index('idx_tenant_docs_org_id', 'tenant_documents', ['organization_id'], unique=False, schema='core')
    op.create_index('idx_tenant_docs_org_type', 'tenant_documents', ['organization_id', 'document_type'], unique=False, schema='core')
    op.create_index('idx_tenant_docs_search_vector', 'tenant_documents', ['search_vector'], unique=False, schema='core', postgresql_using='gin')
    op.create_index('idx_tenant_docs_tags', 'tenant_documents', ['tags'], unique=False, schema='core', postgresql_using='gin')
    op.create_index(op.f('ix_core_tenant_documents_active'), 'tenant_documents', ['active'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_documents_category'), 'tenant_documents', ['category'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_documents_document_type'), 'tenant_documents', ['document_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_documents_organization_id'), 'tenant_documents', ['organization_id'], unique=False, schema='core')
    op.create_table('tenant_prompts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique prompt identifier'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization this prompt belongs to'),
    sa.Column('prompt_key', sa.String(length=255), nullable=False, comment="Key matching PromptRegistry (e.g., 'product.search.intent')"),
    sa.Column('scope', sa.String(length=20), nullable=False, comment="Override scope: 'org' (organization) or 'user' (user-specific)"),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User ID for user-scope prompts (null for org-scope)'),
    sa.Column('template', sa.Text(), nullable=False, comment='The prompt template text with {variable} placeholders'),
    sa.Column('description', sa.Text(), nullable=True, comment="Description of this prompt's purpose"),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Semantic version of this prompt'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metadata (required_variables, temperature, max_tokens, model)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this override is active'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'prompt_key', 'scope', 'user_id', name='uq_org_prompt_key_scope_user'),
    schema='core'
    )
    op.create_index('idx_tenant_prompts_active', 'tenant_prompts', ['is_active'], unique=False, schema='core')
    op.create_index('idx_tenant_prompts_key', 'tenant_prompts', ['prompt_key'], unique=False, schema='core')
    op.create_index('idx_tenant_prompts_org_id', 'tenant_prompts', ['organization_id'], unique=False, schema='core')
    op.create_index('idx_tenant_prompts_org_key_scope', 'tenant_prompts', ['organization_id', 'prompt_key', 'scope'], unique=False, schema='core')
    op.create_index('idx_tenant_prompts_scope', 'tenant_prompts', ['scope'], unique=False, schema='core')
    op.create_index('idx_tenant_prompts_user_id', 'tenant_prompts', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_prompts_is_active'), 'tenant_prompts', ['is_active'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_prompts_organization_id'), 'tenant_prompts', ['organization_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tenant_prompts_user_id'), 'tenant_prompts', ['user_id'], unique=False, schema='core')
    op.create_table('payment_schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['credit.credit_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='credit'
    )
    op.create_index(op.f('ix_credit_payment_schedule_items_account_id'), 'payment_schedule_items', ['account_id'], unique=False, schema='credit')
    op.create_index(op.f('ix_credit_payment_schedule_items_due_date'), 'payment_schedule_items', ['due_date'], unique=False, schema='credit')
    op.create_index(op.f('ix_credit_payment_schedule_items_id'), 'payment_schedule_items', ['id'], unique=False, schema='credit')
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('REGULAR', 'MINIMUM', 'FULL', 'EXTRA', 'EARLY', 'LATE', name='paymenttype'), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'DEBIT_CARD', 'CREDIT_CARD', 'CASH', 'CHECK', 'DIRECT_DEBIT', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('interest_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('charges_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['credit.credit_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='credit'
    )
    op.create_index(op.f('ix_credit_payments_account_id'), 'payments', ['account_id'], unique=False, schema='credit')
    op.create_index(op.f('ix_credit_payments_id'), 'payments', ['id'], unique=False, schema='credit')
    op.create_index(op.f('ix_credit_payments_reference_number'), 'payments', ['reference_number'], unique=True, schema='credit')
    op.create_index(op.f('ix_credit_payments_status'), 'payments', ['status'], unique=False, schema='credit')
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('user_messages', sa.Integer(), nullable=True),
    sa.Column('bot_messages', sa.Integer(), nullable=True),
    sa.Column('intent_detected', sa.String(length=100), nullable=True),
    sa.Column('products_shown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversion_stage', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['ecommerce.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index(op.f('ix_ecommerce_conversations_session_id'), 'conversations', ['session_id'], unique=False, schema='ecommerce')
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('shipping_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shipping_method', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('expected_delivery', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['ecommerce.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index('idx_orders_customer', 'orders', ['customer_id'], unique=False, schema='ecommerce')
    op.create_index('idx_orders_customer_status_date', 'orders', ['customer_id', 'status', 'order_date'], unique=False, schema='ecommerce')
    op.create_index('idx_orders_date', 'orders', ['order_date'], unique=False, schema='ecommerce')
    op.create_index('idx_orders_payment_status', 'orders', ['payment_status'], unique=False, schema='ecommerce')
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_orders_order_number'), 'orders', ['order_number'], unique=True, schema='ecommerce')
    op.create_table('subcategories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ecommerce.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=200), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.Enum('GENERAL_PRACTICE', 'CARDIOLOGY', 'DERMATOLOGY', 'EMERGENCY', 'ENDOCRINOLOGY', 'GASTROENTEROLOGY', 'GYNECOLOGY', 'NEUROLOGY', 'ONCOLOGY', 'OPHTHALMOLOGY', 'ORTHOPEDICS', 'PEDIATRICS', 'PSYCHIATRY', 'PULMONOLOGY', 'RADIOLOGY', 'SURGERY', 'UROLOGY', name='doctorspecialty'), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('triage_priority', sa.Enum('RESUSCITATION', 'EMERGENT', 'URGENT', 'LESS_URGENT', 'NON_URGENT', name='triagepriority'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED', name='appointmentstatus'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_telemedicine', sa.Boolean(), nullable=True),
    sa.Column('video_call_url', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('prescriptions', sa.JSON(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['healthcare.doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['healthcare.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='healthcare'
    )
    op.create_index(op.f('ix_healthcare_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False, schema='healthcare')
    op.create_index(op.f('ix_healthcare_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False, schema='healthcare')
    op.create_index(op.f('ix_healthcare_appointments_id'), 'appointments', ['id'], unique=False, schema='healthcare')
    op.create_index(op.f('ix_healthcare_appointments_patient_id'), 'appointments', ['patient_id'], unique=False, schema='healthcare')
    op.create_index(op.f('ix_healthcare_appointments_status'), 'appointments', ['status'], unique=False, schema='healthcare')
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_versions_active', 'prompt_versions', ['is_active'], unique=False)
    op.create_index('ix_prompt_versions_prompt_id', 'prompt_versions', ['prompt_id'], unique=False)
    op.create_index('ix_prompt_versions_version', 'prompt_versions', ['version'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('message_format', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ecommerce.conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index(op.f('ix_ecommerce_messages_user_phone'), 'messages', ['user_phone'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_messages_whatsapp_message_id'), 'messages', ['whatsapp_message_id'], unique=True, schema='ecommerce')
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('specs', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('tax_percentage', sa.Float(), nullable=True),
    sa.Column('external_code', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('technical_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('on_sale', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='check_price_positive'),
    sa.CheckConstraint('stock >= 0', name='check_stock_non_negative'),
    sa.ForeignKeyConstraint(['brand_id'], ['ecommerce.brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['ecommerce.categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['ecommerce.subcategories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index('idx_products_active', 'products', ['active'], unique=False, schema='ecommerce')
    op.create_index('idx_products_brand', 'products', ['brand_id'], unique=False, schema='ecommerce')
    op.create_index('idx_products_category', 'products', ['category_id'], unique=False, schema='ecommerce')
    op.create_index('idx_products_description_trgm', 'products', ['description'], unique=False, schema='ecommerce', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('idx_products_embedding_hnsw', 'products', ['embedding'], unique=False, schema='ecommerce', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_products_featured', 'products', ['featured'], unique=False, schema='ecommerce')
    op.create_index('idx_products_name_trgm', 'products', ['name'], unique=False, schema='ecommerce', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_products_price', 'products', ['price'], unique=False, schema='ecommerce')
    op.create_index('idx_products_sale', 'products', ['on_sale'], unique=False, schema='ecommerce')
    op.create_index('idx_products_search', 'products', ['search_vector'], unique=False, schema='ecommerce', postgresql_using='gin')
    op.create_index('idx_products_stock', 'products', ['stock'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_products_active'), 'products', ['active'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_products_featured'), 'products', ['featured'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_products_name'), 'products', ['name'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_products_on_sale'), 'products', ['on_sale'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_products_price'), 'products', ['price'], unique=False, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_products_sku'), 'products', ['sku'], unique=True, schema='ecommerce')
    op.create_index(op.f('ix_ecommerce_products_stock'), 'products', ['stock'], unique=False, schema='ecommerce')
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=50), nullable=True),
    sa.Column('product_specs', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ecommerce.orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index('idx_order_items_order', 'order_items', ['order_id'], unique=False, schema='ecommerce')
    op.create_index('idx_order_items_product', 'order_items', ['product_id'], unique=False, schema='ecommerce')
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_reason', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_table('product_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('attribute_type', sa.String(length=50), nullable=True),
    sa.Column('is_searchable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_product_attribute_name'),
    schema='ecommerce'
    )
    op.create_index('idx_product_attributes_name', 'product_attributes', ['name'], unique=False, schema='ecommerce')
    op.create_index('idx_product_attributes_product', 'product_attributes', ['product_id'], unique=False, schema='ecommerce')
    op.create_index('idx_product_attributes_searchable', 'product_attributes', ['is_searchable'], unique=False, schema='ecommerce')
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_index('idx_product_images_primary', 'product_images', ['is_primary'], unique=False, schema='ecommerce')
    op.create_index('idx_product_images_product', 'product_images', ['product_id'], unique=False, schema='ecommerce')
    op.create_index('idx_product_images_sort', 'product_images', ['sort_order'], unique=False, schema='ecommerce')
    op.create_table('product_inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('inquiry_type', sa.String(length=50), nullable=False),
    sa.Column('inquiry_text', sa.Text(), nullable=True),
    sa.Column('budget_mentioned', sa.Float(), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ecommerce.categories.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['ecommerce.customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_table('product_promotions',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('promotion_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['ecommerce.promotions.id'], ),
    schema='ecommerce'
    )
    op.create_table('product_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['ecommerce.customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce'
    )
    # NOTE: Removed auto-generated op.drop_table('alembic_version')
    # This table is managed by Alembic itself and should not be dropped
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed auto-generated op.create_table('alembic_version')
    # This table is managed by Alembic itself and should not be recreated
    op.drop_table('stock_movements', schema='ecommerce')
    op.drop_table('product_reviews', schema='ecommerce')
    op.drop_table('product_promotions', schema='ecommerce')
    op.drop_table('product_inquiries', schema='ecommerce')
    op.drop_index('idx_product_images_sort', table_name='product_images', schema='ecommerce')
    op.drop_index('idx_product_images_product', table_name='product_images', schema='ecommerce')
    op.drop_index('idx_product_images_primary', table_name='product_images', schema='ecommerce')
    op.drop_table('product_images', schema='ecommerce')
    op.drop_index('idx_product_attributes_searchable', table_name='product_attributes', schema='ecommerce')
    op.drop_index('idx_product_attributes_product', table_name='product_attributes', schema='ecommerce')
    op.drop_index('idx_product_attributes_name', table_name='product_attributes', schema='ecommerce')
    op.drop_table('product_attributes', schema='ecommerce')
    op.drop_table('price_history', schema='ecommerce')
    op.drop_index('idx_order_items_product', table_name='order_items', schema='ecommerce')
    op.drop_index('idx_order_items_order', table_name='order_items', schema='ecommerce')
    op.drop_table('order_items', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_products_stock'), table_name='products', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_products_sku'), table_name='products', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_products_price'), table_name='products', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_products_on_sale'), table_name='products', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_products_name'), table_name='products', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_products_featured'), table_name='products', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_products_active'), table_name='products', schema='ecommerce')
    op.drop_index('idx_products_stock', table_name='products', schema='ecommerce')
    op.drop_index('idx_products_search', table_name='products', schema='ecommerce', postgresql_using='gin')
    op.drop_index('idx_products_sale', table_name='products', schema='ecommerce')
    op.drop_index('idx_products_price', table_name='products', schema='ecommerce')
    op.drop_index('idx_products_name_trgm', table_name='products', schema='ecommerce', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_products_featured', table_name='products', schema='ecommerce')
    op.drop_index('idx_products_embedding_hnsw', table_name='products', schema='ecommerce', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_products_description_trgm', table_name='products', schema='ecommerce', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('idx_products_category', table_name='products', schema='ecommerce')
    op.drop_index('idx_products_brand', table_name='products', schema='ecommerce')
    op.drop_index('idx_products_active', table_name='products', schema='ecommerce')
    op.drop_table('products', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_messages_whatsapp_message_id'), table_name='messages', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_messages_user_phone'), table_name='messages', schema='ecommerce')
    op.drop_table('messages', schema='ecommerce')
    op.drop_index('ix_prompt_versions_version', table_name='prompt_versions')
    op.drop_index('ix_prompt_versions_prompt_id', table_name='prompt_versions')
    op.drop_index('ix_prompt_versions_active', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_healthcare_appointments_status'), table_name='appointments', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_appointments_patient_id'), table_name='appointments', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_appointments_id'), table_name='appointments', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_appointments_doctor_id'), table_name='appointments', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_appointments_appointment_date'), table_name='appointments', schema='healthcare')
    op.drop_table('appointments', schema='healthcare')
    op.drop_table('subcategories', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_orders_order_number'), table_name='orders', schema='ecommerce')
    op.drop_index('idx_orders_status', table_name='orders', schema='ecommerce')
    op.drop_index('idx_orders_payment_status', table_name='orders', schema='ecommerce')
    op.drop_index('idx_orders_date', table_name='orders', schema='ecommerce')
    op.drop_index('idx_orders_customer_status_date', table_name='orders', schema='ecommerce')
    op.drop_index('idx_orders_customer', table_name='orders', schema='ecommerce')
    op.drop_table('orders', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_conversations_session_id'), table_name='conversations', schema='ecommerce')
    op.drop_table('conversations', schema='ecommerce')
    op.drop_index(op.f('ix_credit_payments_status'), table_name='payments', schema='credit')
    op.drop_index(op.f('ix_credit_payments_reference_number'), table_name='payments', schema='credit')
    op.drop_index(op.f('ix_credit_payments_id'), table_name='payments', schema='credit')
    op.drop_index(op.f('ix_credit_payments_account_id'), table_name='payments', schema='credit')
    op.drop_table('payments', schema='credit')
    op.drop_index(op.f('ix_credit_payment_schedule_items_id'), table_name='payment_schedule_items', schema='credit')
    op.drop_index(op.f('ix_credit_payment_schedule_items_due_date'), table_name='payment_schedule_items', schema='credit')
    op.drop_index(op.f('ix_credit_payment_schedule_items_account_id'), table_name='payment_schedule_items', schema='credit')
    op.drop_table('payment_schedule_items', schema='credit')
    op.drop_index(op.f('ix_core_tenant_prompts_user_id'), table_name='tenant_prompts', schema='core')
    op.drop_index(op.f('ix_core_tenant_prompts_organization_id'), table_name='tenant_prompts', schema='core')
    op.drop_index(op.f('ix_core_tenant_prompts_is_active'), table_name='tenant_prompts', schema='core')
    op.drop_index('idx_tenant_prompts_user_id', table_name='tenant_prompts', schema='core')
    op.drop_index('idx_tenant_prompts_scope', table_name='tenant_prompts', schema='core')
    op.drop_index('idx_tenant_prompts_org_key_scope', table_name='tenant_prompts', schema='core')
    op.drop_index('idx_tenant_prompts_org_id', table_name='tenant_prompts', schema='core')
    op.drop_index('idx_tenant_prompts_key', table_name='tenant_prompts', schema='core')
    op.drop_index('idx_tenant_prompts_active', table_name='tenant_prompts', schema='core')
    op.drop_table('tenant_prompts', schema='core')
    op.drop_index(op.f('ix_core_tenant_documents_organization_id'), table_name='tenant_documents', schema='core')
    op.drop_index(op.f('ix_core_tenant_documents_document_type'), table_name='tenant_documents', schema='core')
    op.drop_index(op.f('ix_core_tenant_documents_category'), table_name='tenant_documents', schema='core')
    op.drop_index(op.f('ix_core_tenant_documents_active'), table_name='tenant_documents', schema='core')
    op.drop_index('idx_tenant_docs_tags', table_name='tenant_documents', schema='core', postgresql_using='gin')
    op.drop_index('idx_tenant_docs_search_vector', table_name='tenant_documents', schema='core', postgresql_using='gin')
    op.drop_index('idx_tenant_docs_org_type', table_name='tenant_documents', schema='core')
    op.drop_index('idx_tenant_docs_org_id', table_name='tenant_documents', schema='core')
    op.drop_index('idx_tenant_docs_org_active', table_name='tenant_documents', schema='core')
    op.drop_index('idx_tenant_docs_category', table_name='tenant_documents', schema='core')
    op.drop_table('tenant_documents', schema='core')
    op.drop_index('idx_tenant_configs_org_id', table_name='tenant_configs', schema='core')
    op.drop_table('tenant_configs', schema='core')
    op.drop_index(op.f('ix_core_tenant_agents_organization_id'), table_name='tenant_agents', schema='core')
    op.drop_index(op.f('ix_core_tenant_agents_enabled'), table_name='tenant_agents', schema='core')
    op.drop_index(op.f('ix_core_tenant_agents_domain_key'), table_name='tenant_agents', schema='core')
    op.drop_index('idx_tenant_agents_org_id', table_name='tenant_agents', schema='core')
    op.drop_index('idx_tenant_agents_enabled', table_name='tenant_agents', schema='core')
    op.drop_index('idx_tenant_agents_domain_key', table_name='tenant_agents', schema='core')
    op.drop_index('idx_tenant_agents_agent_type', table_name='tenant_agents', schema='core')
    op.drop_table('tenant_agents', schema='core')
    op.drop_index(op.f('ix_core_organization_users_user_id'), table_name='organization_users', schema='core')
    op.drop_index(op.f('ix_core_organization_users_organization_id'), table_name='organization_users', schema='core')
    op.drop_index('idx_org_users_user_id', table_name='organization_users', schema='core')
    op.drop_index('idx_org_users_role', table_name='organization_users', schema='core')
    op.drop_index('idx_org_users_org_id', table_name='organization_users', schema='core')
    op.drop_table('organization_users', schema='core')
    op.drop_index('ix_prompts_key_active', table_name='prompts')
    op.drop_index(op.f('ix_prompts_key'), table_name='prompts')
    op.drop_index('ix_prompts_is_dynamic', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_healthcare_patients_phone'), table_name='patients', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_patients_national_id'), table_name='patients', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_patients_medical_record_number'), table_name='patients', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_patients_id'), table_name='patients', schema='healthcare')
    op.drop_table('patients', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_doctors_license_number'), table_name='doctors', schema='healthcare')
    op.drop_index(op.f('ix_healthcare_doctors_id'), table_name='doctors', schema='healthcare')
    op.drop_table('doctors', schema='healthcare')
    op.drop_index(op.f('ix_ecommerce_promotions_promo_code'), table_name='promotions', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_promotions_active'), table_name='promotions', schema='ecommerce')
    op.drop_table('promotions', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_customers_phone_number'), table_name='customers', schema='ecommerce')
    op.drop_index('idx_customers_name', table_name='customers', schema='ecommerce')
    op.drop_index('idx_customers_active', table_name='customers', schema='ecommerce')
    op.drop_table('customers', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_categories_external_id'), table_name='categories', schema='ecommerce')
    op.drop_index('idx_categories_sort', table_name='categories', schema='ecommerce')
    op.drop_index('idx_categories_active', table_name='categories', schema='ecommerce')
    op.drop_table('categories', schema='ecommerce')
    op.drop_index('idx_brands_name_trgm', table_name='brands', schema='ecommerce', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_brands_active', table_name='brands', schema='ecommerce')
    op.drop_table('brands', schema='ecommerce')
    op.drop_index(op.f('ix_ecommerce_analytics_metric_name'), table_name='analytics', schema='ecommerce')
    op.drop_table('analytics', schema='ecommerce')
    op.drop_index(op.f('ix_credit_credit_accounts_status'), table_name='credit_accounts', schema='credit')
    op.drop_index(op.f('ix_credit_credit_accounts_id'), table_name='credit_accounts', schema='credit')
    op.drop_index(op.f('ix_credit_credit_accounts_customer_id'), table_name='credit_accounts', schema='credit')
    op.drop_index(op.f('ix_credit_credit_accounts_account_number'), table_name='credit_accounts', schema='credit')
    op.drop_table('credit_accounts', schema='credit')
    op.drop_index(op.f('ix_core_users_username'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_index('idx_users_username', table_name='users', schema='core')
    op.drop_index('idx_users_email', table_name='users', schema='core')
    op.drop_index('idx_users_disabled', table_name='users', schema='core')
    op.drop_index('idx_users_created_at', table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index(op.f('ix_core_organizations_status'), table_name='organizations', schema='core')
    op.drop_index(op.f('ix_core_organizations_slug'), table_name='organizations', schema='core')
    op.drop_index('idx_organizations_status', table_name='organizations', schema='core')
    op.drop_index('idx_organizations_slug', table_name='organizations', schema='core')
    op.drop_index('idx_organizations_mode', table_name='organizations', schema='core')
    op.drop_index('idx_organizations_created_at', table_name='organizations', schema='core')
    op.drop_table('organizations', schema='core')
    op.drop_index('idx_domain_configs_priority', table_name='domain_configs', schema='core')
    op.drop_index('idx_domain_configs_enabled', table_name='domain_configs', schema='core')
    op.drop_table('domain_configs', schema='core')
    op.drop_index(op.f('ix_core_contact_domains_wa_id'), table_name='contact_domains', schema='core')
    op.drop_index(op.f('ix_core_contact_domains_domain'), table_name='contact_domains', schema='core')
    op.drop_index('idx_contact_domains_wa_id', table_name='contact_domains', schema='core')
    op.drop_index('idx_contact_domains_method', table_name='contact_domains', schema='core')
    op.drop_index('idx_contact_domains_domain', table_name='contact_domains', schema='core')
    op.drop_index('idx_contact_domains_assigned_at', table_name='contact_domains', schema='core')
    op.drop_table('contact_domains', schema='core')
    op.drop_index(op.f('ix_core_company_knowledge_document_type'), table_name='company_knowledge', schema='core')
    op.drop_index(op.f('ix_core_company_knowledge_category'), table_name='company_knowledge', schema='core')
    op.drop_index(op.f('ix_core_company_knowledge_active'), table_name='company_knowledge', schema='core')
    op.drop_index('idx_knowledge_type_active', table_name='company_knowledge', schema='core')
    op.drop_index('idx_knowledge_tags', table_name='company_knowledge', schema='core', postgresql_using='gin')
    op.drop_index('idx_knowledge_search_vector', table_name='company_knowledge', schema='core', postgresql_using='gin')
    op.drop_index('idx_knowledge_embedding_hnsw', table_name='company_knowledge', schema='core', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_knowledge_category', table_name='company_knowledge', schema='core')
    op.drop_table('company_knowledge', schema='core')
    # ### end Alembic commands ###
