"""
Create Incident Use Case.

Creates incidents in the new soporte schema from conversational flow data.
This replaces the immediate ticket creation with a more structured approach.
"""

import logging
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.db.soporte import Incident, IncidentCategory

logger = logging.getLogger(__name__)

# Priority mapping from numeric selection to enum value
PRIORITY_MAP = {
    "1": "critical",
    "2": "high",
    "3": "medium",
    "4": "low",
    "critico": "critical",
    "alto": "high",
    "medio": "medium",
    "bajo": "low",
}

# Priority display names
PRIORITY_DISPLAY = {
    "critical": "Critico",
    "high": "Alto",
    "medium": "Medio",
    "low": "Bajo",
}


class CreateIncidentUseCase:
    """
    Use Case: Create Incident

    Creates a new incident in the soporte.incidents table from
    data collected during the conversational flow.

    The folio is auto-generated by a database trigger.

    Responsibilities:
    - Create incident with collected data
    - Link to category (if available)
    - Return incident info for confirmation message
    """

    def __init__(self, db: AsyncSession):
        """
        Initialize use case with database session.

        Args:
            db: Async database session
        """
        self.db = db

    async def execute(
        self,
        user_phone: str,
        description: str,
        priority: str,
        category_code: str = "GENERAL",
        conversation_id: str | UUID | None = None,
        user_name: str | None = None,
        incident_type: str = "incident",
        organization_id: UUID | None = None,
        meta_data: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Create a new incident in soporte schema.

        Args:
            user_phone: WhatsApp phone number
            description: Full description from conversational flow
            priority: Priority level (1-4, or critical/high/medium/low)
            category_code: Category code (TECNICO, FACTURACION, etc.)
            conversation_id: Link to conversation
            user_name: User's name if known
            incident_type: Type (incident, feedback, question, suggestion)
            organization_id: Organization ID for multi-tenant
            meta_data: Additional context

        Returns:
            Dictionary with created incident info including folio

        Example:
            use_case = CreateIncidentUseCase(db)
            result = await use_case.execute(
                user_phone="+521234567890",
                description="El modulo de facturacion no genera PDF",
                priority="2",
                category_code="FACTURACION",
            )
            # Returns: {"folio": "INC-2024-00001", "priority": "Alto", ...}
        """
        try:
            # Normalize priority
            normalized_priority = self._normalize_priority(priority)

            # Get category ID
            category_id = await self._get_category_id(category_code)

            # Convert conversation_id to UUID
            conv_id = None
            if conversation_id:
                if isinstance(conversation_id, str):
                    try:
                        conv_id = UUID(conversation_id)
                    except ValueError:
                        logger.warning(f"Invalid conversation_id: {conversation_id}")
                else:
                    conv_id = conversation_id

            # Auto-generate subject from description
            subject = description[:100]
            if len(description) > 100:
                last_space = subject.rfind(" ")
                if last_space > 50:
                    subject = subject[:last_space]
                subject += "..."

            # Create incident (folio is auto-generated by DB trigger)
            incident = Incident(
                organization_id=organization_id,
                user_phone=user_phone,
                user_name=user_name,
                conversation_id=conv_id,
                incident_type=incident_type,
                category_id=category_id,
                subject=subject,
                description=description,
                priority=normalized_priority,
                status="open",
                source="whatsapp",
                meta_data=meta_data or {},
            )

            self.db.add(incident)
            await self.db.commit()
            await self.db.refresh(incident)

            result = {
                "id": str(incident.id),
                "folio": incident.folio,
                "incident_type": incident.incident_type,
                "subject": incident.subject,
                "status": incident.status,
                "priority": normalized_priority,
                "priority_display": PRIORITY_DISPLAY.get(normalized_priority, normalized_priority),
                "category_code": category_code,
                "created_at": incident.created_at.isoformat() if incident.created_at else None,
            }

            logger.info(
                f"Created incident: {incident.folio} "
                f"(type={incident_type}, priority={normalized_priority})"
            )
            return result

        except Exception as e:
            await self.db.rollback()
            logger.error(f"Error creating incident: {e}")
            raise

    def _normalize_priority(self, priority: str) -> str:
        """
        Normalize priority input to enum value.

        Args:
            priority: User input (1-4 or text)

        Returns:
            Normalized priority string
        """
        priority_lower = priority.lower().strip()
        return PRIORITY_MAP.get(priority_lower, "medium")

    async def _get_category_id(self, category_code: str) -> UUID | None:
        """
        Get category ID from code.

        Args:
            category_code: Category code (TECNICO, FACTURACION, etc.)

        Returns:
            UUID of the category or None
        """
        try:
            result = await self.db.execute(
                select(IncidentCategory.id).where(
                    IncidentCategory.code == category_code.upper(),
                    IncidentCategory.is_active == True,  # noqa: E712
                )
            )
            category = result.scalar_one_or_none()
            return category
        except Exception as e:
            logger.warning(f"Could not find category {category_code}: {e}")
            return None

    @staticmethod
    def infer_category_code(description: str) -> str:
        """
        Infer category code from description keywords.

        Args:
            description: Incident description

        Returns:
            Inferred category code
        """
        description_lower = description.lower()

        # Technical keywords
        if any(kw in description_lower for kw in [
            "error", "falla", "bug", "no funciona", "problema",
            "se cae", "lento", "no carga", "pantalla", "mensaje de error"
        ]):
            return "TECNICO"

        # Billing keywords
        if any(kw in description_lower for kw in [
            "factura", "cfdi", "timbrado", "sat", "cancelar",
            "folio", "comprobante", "impuesto"
        ]):
            return "FACTURACION"

        # Training keywords
        if any(kw in description_lower for kw in [
            "capacitacion", "curso", "aprender", "manual", "tutorial",
            "entrenamiento", "como usar"
        ]):
            return "CAPACITACION"

        # Module-specific
        if any(kw in description_lower for kw in ["inventario", "almacen", "stock"]):
            return "INVENTARIO"

        if any(kw in description_lower for kw in ["nomina", "empleado", "sueldo"]):
            return "NOMINA"

        if any(kw in description_lower for kw in ["contabilidad", "balance", "poliza"]):
            return "CONTABILIDAD"

        return "GENERAL"
